import { Platform } from 'react-native';
import { cardShadow, tournamentColors } from './tournamentUi';

export const authUi = {
  screen: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 32,
  },
  hero: {
    borderRadius: 18,
    padding: 24,
    backgroundColor: '#0f172a',
    overflow: 'hidden',
    marginBottom: 0,
  },
  heroGlow: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(37, 99, 235, 0.35)',
  },
  heroEyebrow: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.1,
    marginBottom: 6,
  },
  heroTitle: {
    color: '#f8fafc',
    fontSize: 26,
    fontWeight: '800',
    lineHeight: 32,
  },
  heroSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  formCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: tournamentColors.borderLight,
    backgroundColor: tournamentColors.white,
    padding: 22,
    ...(Platform.OS === 'web' ? cardShadow : { elevation: 2 }),
  },
  mobileIntro: {
    marginBottom: 16,
    paddingVertical: 4,
    gap: 6,
  },
  mobileIntroEyebrow: {
    color: tournamentColors.primary,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.1,
  },
  mobileIntroSubtitle: {
    color: tournamentColors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  sideFeatureList: {
    gap: 14,
    paddingTop: 18,
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.12)',
  },
  sidePanel: {
    borderRadius: 18,
    padding: 24,
    backgroundColor: '#0f172a',
    overflow: 'hidden',
    width: '100%',
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: tournamentColors.text,
    marginBottom: 4,
  },
  formSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: tournamentColors.textMuted,
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: tournamentColors.text,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: tournamentColors.border,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    color: tournamentColors.text,
    backgroundColor: '#fafbfc',
  },
  inputError: {
    borderColor: '#fca5a5',
    backgroundColor: '#fef2f2',
  },
  fieldError: {
    color: tournamentColors.error,
    fontSize: 12,
    marginTop: 6,
  },
  errorBanner: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
    marginBottom: 14,
  },
  errorBannerText: {
    color: '#b91c1c',
    fontSize: 13,
    lineHeight: 18,
  },
  linkText: {
    color: tournamentColors.primary,
    fontWeight: '700',
    fontSize: 14,
  },
  mutedText: {
    color: tournamentColors.textMuted,
    fontSize: 14,
    textAlign: 'center',
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 0,
  },
  featureIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  landingImageCard: {
    overflow: 'hidden',
    marginBottom: 20,
    backgroundColor: '#0f172a',
  },
  landingScrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
  },
  landingBody: {
    paddingHorizontal: 20,
  },
  landingImage: {
    width: '100%',
    height: 280,
  },
  landingImageOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingVertical: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
  },
  successBanner: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#a7f3d0',
    marginBottom: 14,
  },
  successBannerText: {
    color: tournamentColors.success,
    fontSize: 13,
    lineHeight: 18,
  },
  stepRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  stepPill: (active, done) => ({
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: done ? '#dbeafe' : active ? '#2563eb' : '#f1f5f9',
    borderWidth: 1,
    borderColor: done ? '#93c5fd' : active ? '#2563eb' : '#e5e7eb',
  }),
  stepPillText: (active, done) => ({
    fontSize: 11,
    fontWeight: '700',
    color: done ? '#1d4ed8' : active ? '#ffffff' : '#64748b',
  }),
  pinRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  pinCell: (active, filled) => ({
    flex: 1,
    height: 52,
    marginHorizontal: 3,
    borderWidth: 1,
    borderColor: active ? tournamentColors.primary : filled ? '#93c5fd' : tournamentColors.border,
    borderRadius: 12,
    backgroundColor: '#fafbfc',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  hintText: {
    fontSize: 12,
    lineHeight: 17,
    color: tournamentColors.textMuted,
    marginBottom: 12,
  },
  matchOk: {
    fontSize: 12,
    color: tournamentColors.success,
    marginBottom: 12,
  },
  matchBad: {
    fontSize: 12,
    color: tournamentColors.error,
    marginBottom: 12,
  },
};
